SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
MAX_FRAMERATE = 60

COLOR_BLACK = (0, 0, 0)

PLAYER_WIDTH = 75
PLAYER_HEIGHT = 75
PLAYER_SPEED = 400
PLAYER_BOTTOM_MARGIN = 40
PLAYER_IMAGE = "images/player-ship.png.png"
# seconds between shots
PLAYER_SHOOT_COOLDOWN = 0.5

LASER_WIDTH = 8
LASER_HEIGHT = 24
LASER_SPEED = 600
LASER_IMAGE = "images/player-laser.png.png"
