SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
MAX_FRAMERATE = 60

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)

GAME_OVER_TEXT = "GAME OVER"
GAME_OVER_FONT_SIZE = 120

PLAYER_WIDTH = 75
PLAYER_HEIGHT = 75
PLAYER_SPEED = 400
PLAYER_BOTTOM_MARGIN = 40
PLAYER_IMAGE = "images/player-ship.png.png"
# seconds between shots
PLAYER_SHOOT_COOLDOWN = 0.5

LASER_WIDTH = 8
LASER_HEIGHT = 24
LASER_SPEED = 600
LASER_IMAGE = "images/player-laser.png.png"

ENEMY_WIDTH = 72
ENEMY_HEIGHT = 75
ENEMY_SPEED = 0
ENEMY_IMAGE = "images/enemy-ship.png.png"

ENEMY_HORIZONTAL_SPACING = 20
ENEMY_VERTICAL_SPACING = 20
ENEMY_TOP_MARGIN = 80
ENEMY_LEFT_MARGIN = 120

ENEMY_LASER_WIDTH = 15
ENEMY_LASER_HEIGHT = 15
ENEMY_LASER_SPEED = 400
ENEMY_LASER_IMAGE = "images/enemy-laser.png.png"

ENEMY_SHOOT_INTERVAL = 0.25
